### ISSUE TITLE
Storing model in pmml broken in latest 0.57 release

### ISSUE THREAD

**Issue by MaxNoe** [jpmml/jpmml-python#3]
Storing a random forest to pmml does not work anymore with the latest release of sklearn2pmml,
see https://travis-ci.org/github/fact-project/aict-tools/jobs/691364313

```
May 26, 2020 3:39:05 PM org.jpmml.sklearn.Main run

INFO: Parsing PKL..

May 26, 2020 3:39:05 PM org.jpmml.sklearn.Main run

SEVERE: Failed to parse PKL

net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.dtype)

	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)

	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)

	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:199)

	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:81)

	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)

	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:102)

	at org.jpmml.sklearn.Main.run(Main.java:161)

	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.dtype)

	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)

	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)

	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:199)

	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:81)

	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)

	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:102)

	at org.jpmml.sklearn.Main.run(Main.java:161)

	at org.jpmml.sklearn.Main.main(Main.java:151)

----------------------------- Captured stderr call -----------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/click/testing.py", line 329, in invoke

    cli.main(args=args or (), prog_name=prog_name, **extra)

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/home/travis/build/fact-project/aict-tools/aict_tools/scripts/train_energy_regressor.py", line 109, in main

    save_model(

  File "/home/travis/build/fact-project/aict-tools/aict_tools/io.py", line 389, in save_model

    sklearn2pmml(pipeline, model_path)

  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/sklearn2pmml/__init__.py", line 266, in sklearn2pmml

    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by MaxNoe** [comment]
Downgrading sklearn2pmml fixed it for the same numpy version,  so I dont think so

**Comment by vruusmann** [comment]
> Downgrading sklearn2pmml fixed it for the same numpy version

OK, that's good to know.

But I don't recall changing absolutely anything about Scikit-Learn conversion (between SkLearn2PMML 0.56.2 and 0.57.0 versions) - it was all about updating/upgrading Java dependencies.

**Comment by vruusmann** [comment]
I managed to break one of my integration tests by upgrading Pandas from 0.25.4 to 1.0.3. But that's a different exception (still related to the changed representation of `ClassDict` classes), not this `numpy.dtype` constructor issue.

I believe this issue is somehow related to replacing Pyrolite dependency with Pickle and Serpent dependencies: https://github.com/jpmml/jpmml-sklearn/commit/81fb840b5b10cf98c0a6aea8b26d745096c43e3a

**Comment by bindernet** [comment]
Thanks Villu. Very mysterious
Just FYI:
Upgraded to latest sklearn2pmml. Seeing the same error using sklearn2pmml() method for pipelines that previously worked on 0.53.0 I believe.
Let me know if there's any details from my env that can help

In [5]: sklearn2pmml.__version__                                                                                                                                                                                
Out[5]: '0.57.0'

In [8]: sklearn2pmml._classpath([])                                                                                                                                                                             
Out[8]: 
['/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-model-metro-1.5.1.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/serpent-1.30.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jaxb-runtime-2.3.2.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/slf4j-api-1.7.30.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-agent-1.5.1.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-tree-api-0.3.9.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-python-1.0.0.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/pickle-1.0.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jakarta.xml.bind-api-2.3.2.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.4.0.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-h2o-1.1.0.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-lightgbm-1.3.0.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-model-1.5.1.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jakarta.activation-api-1.2.1.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jcommander-1.72.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-logger-3.30.0.3.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/gson-2.6.2.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-converter-1.4.1.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/guava-21.0.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.30.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/istack-commons-runtime-3.0.8.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.6.0.jar',
 '/home/xxx/.local/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-genmodel-3.30.0.3.jar']

**Comment by MaxNoe** [comment]
I just reproduced this with a fresh virtualenv and a rather minimal example:

```python
from sklearn2pmml import sklearn2pmml, PMMLPipeline
from sklearn.ensemble import RandomForestClassifier
import numpy as np


X = np.random.normal(size=(1000, 5))
y = np.random.randint(0, 2, 1000)

clf = RandomForestClassifier()
clf.fit(X, y)

pipeline = PMMLPipeline([('rf', clf)])
pipeline.target_field = 'target'
pipeline.active_fields = np.array(list('abcde'))
sklearn2pmml(pipeline, 'test.pmml')
```

Steps to reproduce
```
python -m venv venv
. venv/bin/activate
pip install scikit-learn sklearn2pmml
python test_pmml.py
```

Error:
```
/home/maxnoe/test_pmml/lib/python3.8/site-packages/sklearn/base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '
/usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
Standard output is empty
Standard error:
May 27, 2020 1:30:47 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 27, 2020 1:30:48 PM org.jpmml.sklearn.Main run
SEVERE: Failed to parse PKL
net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.dtype)
	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:199)
	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:81)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:102)
	at org.jpmml.sklearn.Main.run(Main.java:161)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.dtype)
	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:759)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:199)
	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:81)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:102)
	at org.jpmml.sklearn.Main.run(Main.java:161)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Traceback (most recent call last):
  File "test_pmml.py", line 15, in <module>
    sklearn2pmml(pipeline, 'test.pmml')
  File "/home/maxnoe/test_pmml/lib/python3.8/site-packages/sklearn2pmml/__init__.py", line 266, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```


pip freeze output:
```
$ pip freeze
joblib==0.15.1
numpy==1.18.4
pandas==1.0.3
python-dateutil==2.8.1
pytz==2020.1
scikit-learn==0.23.1
scipy==1.4.1
six==1.15.0
sklearn-pandas==1.8.0
sklearn2pmml==0.57.0
threadpoolctl==2.0.0
```

**Comment by MaxNoe** [comment]
It works fine with 0.56., just issues a couple of warnings:

```
/home/maxnoe/test_pmml/lib/python3.8/site-packages/sklearn/base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '
/usr/lib/python3.8/subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
```
